implemented the ethcall
maticnetwork/bor pull request #164
Opened 2021-08-10 08:14 UTC by temaniarpit27

2021-08-10 17:35 UTC, jdkanani commented
@temaniarpit27 few things -- 

1. Does it contain a bor receipt? If not, we should add it.
2. Can we convert it to `bor_` instead of `eth_`?
3. Allow it to have receipts by both block number and block hash by using `blockNrOrHash rpc.BlockNumberOrHash` as param instead of just `blockNumber`. We can rename the method to `bor_getTransactionReceiptsByBlock`

2021-08-11 09:07 UTC, jdkanani requested changes

2021-08-11 09:07 UTC, jdkanani commented on internal/ethapi/api.go
> +		fields = s.appendRPCMarshalBorTransaction(ctx, block, fields, true)
This won't add bor tx receipt. It will just append bor transaction.

2021-08-11 09:07 UTC, jdkanani commented on internal/ethapi/api.go
> +	blockHash := rawdb.ReadCanonicalHash(s.b.ChainDb(), blockNumber)
Also, you don't need to methods (byBlockNumber or byBlockHash). One method can take block number or block hash. 

```
func (s *PublicBlockChainAPI) GetTransactionReceiptsByBlock(ctx context.Context, blockNrOrHash rpc.BlockNumberOrHash) ([]map[string]interface{}, error) {
      // Retrieve the block to act as the gas ceiling
		block, err := b.BlockByNumberOrHash(ctx, blockNrOrHash)
		if err != nil {
			return nil, err
		}
                 ... 
}
```

2021-08-12 08:50 UTC, temaniarpit27 commented
@jdkanani @ssandeep please review

2021-08-12 11:03 UTC, jdkanani approved these changes

2021-08-12 17:21 UTC, ssandeep approved these changes

2021-08-12 17:34 UTC, merged