Genesis change fix
maticnetwork/bor pull request #252
Opened 2021-12-03 14:06 UTC by temaniarpit27

2021-12-03 15:18 UTC, vcastellm approved these changes
LGTM

2021-12-03 15:25 UTC, jdkanani requested changes
@ferranbt

2021-12-03 15:25 UTC, jdkanani commented on params/config.go
> +	BlockAlloc               map[string]interface{} `json:"block_alloc"`
```suggestion
	BlockAlloc               map[string]interface{} `json:"blockAlloc"`
```

2021-12-03 15:25 UTC, jdkanani commented on params/config.go
> +				"0": "",
Shouldn't this line be the object?

2021-12-03 15:25 UTC, jdkanani commented on params/config.go
> +				"0": "",
Shouldn't this line be the object?

2021-12-03 17:22 UTC, jdkanani approved these changes

2021-12-03 18:51 UTC, ssandeep approved these changes

2021-12-03 18:52 UTC, merged

2021-12-07 19:49 UTC, miohtama commented
This change looks pretty important, but does not have much metadata and discussion attached to it. What is this change about?