v0.2.13 candidate
maticnetwork/bor pull request #294
Opened 2022-01-11 11:07 UTC by vcastellm

v0.2.13 release changes to be included in master

2022-01-11 13:56 UTC, ssandeep requested changes

2022-01-11 13:56 UTC, ssandeep commented on builder/files/genesis-mainnet-v1.json
>        "period": 2,
Period and BackupMultiplier are objects now. Please refer launch repo.

2022-01-11 15:50 UTC, ssandeep approved these changes

2022-01-12 15:09 UTC, ferranbt approved these changes

2022-01-13 08:37 UTC, merged