Added bor fingerprint
maticnetwork/bor pull request #308
Opened 2022-01-21 12:59 UTC by Shivam691999

Added bor fingerprint command to the new CLI. It works offline and shows all the properties listed in https://linear.app/matic/issue/POS-55/bor-fingerprint.

2022-01-21 13:32 UTC, ferranbt requested changes
Some initial review.

2022-01-21 13:32 UTC, ferranbt commented on internal/cli/bor_fingerprint.go
> +	v, _ := mem.VirtualMemory()
Do never skip an error.

2022-01-21 13:32 UTC, ferranbt commented on internal/cli/bor_fingerprint.go
> +	totalMem := math.Floor(float64(v.Total)/(1024*1024*1024)*100) / 100
Please create a function for this.

2022-01-21 13:32 UTC, ferranbt commented on internal/cli/bor_fingerprint.go
> +	osDetails := fmt.Sprintf("OS : %s %s ", osName, osVer)
See other commands, for structured info like this, we are not using Output directly but a prettify version of it using `formatKV` and `formatList`.

2022-02-11 11:33 UTC, ssandeep submitted a review, later dismissed

2022-02-14 12:15 UTC, manav2401 submitted a review, later dismissed

2022-02-15 10:07 UTC, vcastellm approved these changes
GLTM but please request against `v0.3.0-dev`

2022-02-16 09:48 UTC, Shivam691999 commented
> GLTM but please request against `v0.3.0-dev`

Done @vcastellm

2022-02-16 11:00 UTC, vcastellm approved these changes

2022-02-16 11:44 UTC, vcastellm requested changes

2022-02-16 12:17 UTC, Shivam691999 commented on internal/cli/bor_fingerprint.go
> +		message := "\nFio package not installed. Install Fio for IOPS Benchmarking :\n\nDebianOS  :  'sudo apt-get update && sudo apt-get install fio -y'\nAWS AMI/CentOS  :  'sudo yum install fio -y'\nOrac
Yes @vcastellm , it already does that!

2022-03-14 09:44 UTC, temaniarpit27 approved these changes

2022-03-14 09:45 UTC, vcastellm approved these changes
LGTM

2022-03-16 07:56 UTC, ferranbt approved these changes

2022-03-16 07:57 UTC, merged