chg : trieTimeout from 60 to 10 mins
maticnetwork/bor pull request #671
Opened 2023-01-15 19:01 UTC by 0xsharma

# Description
In this PR we resolve an issue of huge rewinds. `trieTimeout`/`trieTimeLimit` is responsible for the frequency of storing block state to the persistent db for a full node. It was set to 60 minutes which resulted in huge gap between states of blocks in the persistent memory. We have reduced this gap to 10 minutes which will increase the frequency of storing the block states to the persistent database.

# Changes

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)
- [ ] Changes only for a subset of nodes

# Checklist

- [x] I have added at least 2 reviewer or the whole pos-v1 team
- [ ] I have added sufficient documentation in code
- [x] I will be resolving comments - if any - by pushing each fix in a separate commit and linking the commit hash in the comment reply

## Testing

- [ ] I have added unit tests
- [ ] I have added tests to CI
- [ ] I have tested this code manually on local environment
- [x] I have tested this code manually on remote devnet using express-cli
- [x] I have tested this code manually on mumbai
- [ ] I have created new e2e tests into express-cli

2023-01-15 19:42 UTC, marcello33 approved these changes

2023-01-15 19:51 UTC, JekaMas approved these changes

2023-01-16 04:14 UTC, pratikspatil024 requested changes
Please update the default values in `config.toml` files as well.

2023-01-16 07:06 UTC, pratikspatil024 approved these changes

2023-01-20 07:00 UTC, closed without merging