consensus/bor : add : devFakeAuthor flag
maticnetwork/bor pull request #697
Opened 2023-01-20 11:52 UTC by 0xsharma

# Description

In this PR, we added `--bor.devfakeauthor` flag. Using this we can run bor as a validator without the requirement of initial validator-set or Heimdall. This flag must be used with `--bor.withoutheimdall`.

# Changes

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)
- [ ] Changes only for a subset of nodes

# Checklist

- [x] I have added at least 2 reviewer or the whole pos-v1 team
- [x] I have added sufficient documentation in code
- [x] I will be resolving comments - if any - by pushing each fix in a separate commit and linking the commit hash in the comment reply

## Testing

- [ ] I have added unit tests
- [ ] I have added tests to CI
- [x] I have tested this code manually on local environment
- [x] I have tested this code manually on remote devnet using express-cli
- [ ] I have tested this code manually on mumbai
- [ ] I have created new e2e tests into express-cli

2023-01-20 12:10 UTC, pratikspatil024 requested changes
1. As we will be using this flag with `bor.withoutheimdall`, I think we should use the same config (`HeimdallConfig`) which `bor.withoutheimdall` uses. Just to keep these flags organised.
2. Please update the docs by running `make docs` once the final place of this flag is decided.

2023-01-20 12:17 UTC, 0xsharma commented
@pratikspatil024 
1. This change is not just related to heimdall. It's a superset of that. This is related to developer mode where we would want a validator node running on bor consensus which can effectively create blocks without need of genesis contracts and heimdall.

2. Yes, this is in draft stage. Once everything is finalized, we will edit the docs.

2023-01-20 12:20 UTC, JekaMas approved these changes

2023-01-22 07:28 UTC, pratikspatil024 approved these changes

2023-01-25 04:40 UTC, temaniarpit27 approved these changes

2023-02-09 06:40 UTC, merged