Increase StateSync Confirmations
maticnetwork/bor pull request #809
Opened 2023-04-05 11:50 UTC by pratikspatil024

2023-04-05 12:36 UTC, temaniarpit27 requested changes

2023-04-05 12:36 UTC, temaniarpit27 commented on builder/files/genesis-testnet-v4.json
> +      "stateSyncConfirmationMultiplyer": {
same here

2023-04-05 12:36 UTC, temaniarpit27 commented on builder/files/genesis-testnet-v4.json
> +      "stateSyncConfirmationMultiplyer": {
ideally this should take care of the delhi hardfork as well.

2023-04-06 03:30 UTC, pratikspatil024 commented on builder/files/genesis-testnet-v4.json
> +      "indoreBlock": 35400000,
Added a [TODO comment](https://github.com/maticnetwork/bor/pull/809/commits/c824746af26f0515304c94f54ff65f745ade22b5) in `mumbai.go` and `config.go` as we cannot comment in the JSON file.

2023-05-11 15:09 UTC, closed without merging