add db.engine flag
maticnetwork/bor pull request #964
Opened 2023-08-16 05:22 UTC by anshalshukla

# Description

With recent changes in geth a new flag was introduced to select upon the database. We already have the required changes after upstream merge, I've just added the flag to select the database.

# Changes

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)
- [ ] Changes only for a subset of nodes

# Breaking changes

N.A

# Nodes audience

N.A

# Checklist

- [x] I have added at least 2 reviewer or the whole pos-v1 team
- [x] I have added sufficient documentation in code
- [x] I will be resolving comments - if any - by pushing each fix in a separate commit and linking the commit hash in the comment reply
- [ ] Created a task in Jira and informed the team for implementation in Erigon client (if applicable)
- [ ] Includes RPC methods changes, and the Notion documentation has been updated

# Cross repository changes

- [ ] This PR requires changes to heimdall
    - In case link the PR here:
- [ ] This PR requires changes to matic-cli
    - In case link the PR here:

## Testing

- [ ] I have added unit tests
- [ ] I have added tests to CI
- [ ] I have tested this code manually on local environment
- [ ] I have tested this code manually on remote devnet using express-cli
- [ ] I have tested this code manually on mumbai
- [ ] I have created new e2e tests into express-cli

### Manual tests

I've tested it locally and it works well.

# Additional comments

[POS-1763](https://polygon.atlassian.net/browse/POS-1723)

2023-08-16 07:33 UTC, manav2401 requested changes
Few nit picks before merging. 
1. Run `make docs` to update the docs at the end. 
2. Update the 9 `config.toml` files with this value (commented) (in `builder` and `packaging` modules). 
3. Update `example_config.toml` in `docs/cli`. 
4. Test it locally to confirm few things like - if pebble db is enabled for fresh node or not, if you start node with leveldb and restart it with pebble are the errors handled correctly or not, etc.

2023-08-16 07:33 UTC, manav2401 commented on internal/cli/server/config.go
> +	DBEngine string `hcl:"dbengine,optional" toml:"dbengine,optional"`
You'll need to add `DBEngine` in the `DefaultConfig` function below. Use `leveldb` as default for now.

2023-08-16 07:33 UTC, manav2401 commented on internal/cli/server/flags.go
> +		Default: "leveldb",
Use `Default: c.cliConfig.DBEngine` instead of hardcoded value.

2023-08-17 06:07 UTC, marcello33 approved these changes

2023-08-17 06:11 UTC, pratikspatil024 approved these changes

2023-08-17 07:55 UTC, 0xsharma approved these changes

2023-08-17 14:49 UTC, merged